name: macro_lens
description: MacroLens helps you effortlessly track your daily macronutrient intake by scanning and recording everything you've eaten. Stay on top of your nutrition goals with real-time insights into your protein, carbohydrate, and fat consumption.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "^3.6.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  simple_barcode_scanner: ^0.3.0
  http: ^1.3.0
  circle_nav_bar: ^2.2.0
  flutterfire_cli: ^1.1.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  provider: ^6.1.2
  firebase_ui_auth: ^1.16.1
  shared_preferences: ^2.0.13
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/images/profile_blank.jpg
    - assets/images/meal_0.jpg
    - assets/images/meal_1.jpg
    - assets/images/meal_2.jpg
    - assets/images/meal_3.jpg
    - assets/videos/scanning_barcode.mp4

dependency_overrides:
  intl: ^0.18.0

