// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

const FirebaseOptions firebaseOptions = FirebaseOptions(
  apiKey: "AIzaSyBo0kfIHdnXd5f3RJBk-vpRVptRBpKwbME",
  authDomain: "macro-c629e.firebaseapp.com",
  projectId: "macro-c629e",
  storageBucket: "macro-c629e.firebasestorage.app",
  messagingSenderId: "1050599037930",
  appId: "1:1050599037930:web:ad31b673ee02cf6e2af093",
  measurementId: "G-YMLCZVQL94"
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo0kfIHdnXd5f3RJBk-vpRVptRBpKwbME',
    appId: '1:1050599037930:web:ad31b673ee02cf6e2af093',
    messagingSenderId: '1050599037930',
    projectId: 'macro-c629e',
    authDomain: 'macro-c629e.firebaseapp.com',
    storageBucket: 'macro-c629e.firebasestorage.app',
    measurementId: 'G-YMLCZVQL94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYl34blO2M8463a70WHScrd7w6LMe0uFw',
    appId: '1:1050599037930:android:0ab72aca1a04f43e2af093',
    messagingSenderId: '1050599037930',
    projectId: 'macro-c629e',
    storageBucket: 'macro-c629e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDRhB8q-veDqO0D_5wyxhZiJJBXCAyMw',
    appId: '1:1050599037930:ios:cf47258f2048705d2af093',
    messagingSenderId: '1050599037930',
    projectId: 'macro-c629e',
    storageBucket: 'macro-c629e.firebasestorage.app',
    iosBundleId: 'com.example.macroLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDRhB8q-veDqO0D_5wyxhZiJJBXCAyMw',
    appId: '1:1050599037930:ios:cf47258f2048705d2af093',
    messagingSenderId: '1050599037930',
    projectId: 'macro-c629e',
    storageBucket: 'macro-c629e.firebasestorage.app',
    iosBundleId: 'com.example.macroLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo0kfIHdnXd5f3RJBk-vpRVptRBpKwbME',
    appId: '1:1050599037930:web:d0e30502cc01905c2af093',
    messagingSenderId: '1050599037930',
    projectId: 'macro-c629e',
    authDomain: 'macro-c629e.firebaseapp.com',
    storageBucket: 'macro-c629e.firebasestorage.app',
    measurementId: 'G-RGPCCBY9BV',
  );

}