name: Deploy to Mac

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into Mac and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no user@192.168.0.147 << 'EOF'
            cd /path/to/project
            git pull origin main
            npm install  # or any dependencies
            npm run build # or start server
            # Add deployment commands like `xcodebuild`, `fastlane`, etc.
          EOF
